### ISSUE TITLE
Need help to understand and implement code to evaluate the model

### ISSUE THREAD

**Issue by hitesh-n** [hitesh-n/FSM-INT-2022#2]
This is a code from tensorflow that is recently added which is used to evaluate the trained object detection model - https://github.com/tensorflow/models/blob/master/research/object_detection/utils/object_detection_evaluation.py 
I kindly request help to understand this code and implement it to evaluate the model I have trained.

**Comment by DEVESHTARASIA** [comment]
Hi, suggest a timing for a meeting on whatsapp
